### ISSUE TITLE
aws_ami.ubuntu query returns no results

### ISSUE THREAD

**Issue by wkhatch** [hashicorp-education/learn-nomad-getting-started#8]
The resource on main.tf line 127, throws "Error: Your query returned no results. Please change your search criteria and try again.

```
Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with data.aws_ami.ubuntu,
│   on main.tf line 127, in data "aws_ami" "ubuntu":
│  127: data "aws_ami" "ubuntu" {
│ 
╵
Operation failed: failed running terraform plan (exit 1)
```

**Comment by VadimVoykin** [comment]
Apparently ubuntu 16.04 ami is not supported any more and hence was removed. I have changed name filter in query to corresponds to later ubuntu jammy 22.04 release. Most of characteristic is the same, so It worked for me well at least in context of hands-on session. Although bulletproof solution from developers would be preferred.
```
diff --git a/aws/main.tf b/aws/main.tf
index ac4f5b8..d54530f 100644
--- a/aws/main.tf
+++ b/aws/main.tf
@@ -130,7 +130,7 @@ data "aws_ami" "ubuntu" {

   filter {
     name   = "name"
-    values = ["ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"]
+    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
}
```
